<#import "parts/common.ftlh" as c>

<@c.page>
    <a href="/main">Login</a>
    <div>Online CR. Convenient cash register solutions for your business</div>
    Online CR is a cash register machine. The cash register is used for cash transactions.
    If you, for example, buy a product or service, then the task of the cash register is to fix the sale and purchase
    transaction and issue a confirmation - a cash register receipt.

</@c.page>